### ISSUE TITLE
Logging in Swiftbar

### ISSUE THREAD

**Issue by Wes974** [unixorn/lima-xbar-plugin#26]
Hi ! I tried using this plugin in SwiftBar but when it is displayed in the menu bar all of the logging are present, it is not the case when using xbar

<img width="1551" alt="SwiftBar" src="https://user-images.githubusercontent.com/7169107/147011080-606f71f3-dbdb-46ae-a18b-445fb6de674e.png">

**Comment by unixorn** [comment]
Huh. I just updated Swiftbar to the latest version and it started doing that for me too.

**Comment by unixorn** [comment]
@Wes974 what appears to have happened is that the most recent Swiftbar update has started capturing `STDERR` in addition to `STDOUT`, causing the logging messages to start spamming the menu.

I've reset the default log level to critical to stifle log messages since they're only used by me when I'm debugging or updating the script.

**Comment by Wes974** [comment]
Oh I see okay, thanks !
